name: mkm-solver-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10,<3.13
  - pip
  - numpy>=1.24
  - scipy>=1.10
  - rich>=13.0
  - matplotlib>=3.7
  - cython>=3.2.4
  - sundials
  - scikits.odes
  - scikits_odes_sundials
  - pip:
      - -e .
